"""Tiny reverse-mode autograd engine on numpy (CPU only).

This file is the differentiation backbone for the nanogpt-cpu objective.
It plays the same role PyTorch plays in karpathy/autoresearch: the research
agent writes ONLY the forward pass and never has to implement gradients.

DO NOT EDIT THIS FILE from the research loop. It is intentionally excluded
from the agent's editable file list. Edit train.py instead.

Supported ops are enough to build embeddings, MLPs, layer norm, and a single
self-attention head:
  +  -  *  /  @ (matmul), sum, mean, relu, gelu, tanh, exp, log, sqrt,
  transpose (last two axes), reshape, softmax (last axis),
  Embedding lookup, and a numerically-stable cross_entropy.
"""
from __future__ import annotations

from typing import Iterable
import numpy as np


def _unbroadcast(grad: np.ndarray, shape: tuple[int, ...]) -> np.ndarray:
    """Reduce `grad` so it matches `shape` (reverse of numpy broadcasting)."""
    while grad.ndim > len(shape):
        grad = grad.sum(axis=0)
    for i, dim in enumerate(shape):
        if dim == 1 and grad.shape[i] != 1:
            grad = grad.sum(axis=i, keepdims=True)
    return grad.reshape(shape)


class Tensor:
    __slots__ = ("data", "grad", "_backward", "_prev")

    def __init__(self, data, _children: tuple["Tensor", ...] = (), _op: str = "") -> None:
        self.data = np.asarray(data, dtype=np.float64)
        self.grad = np.zeros_like(self.data)
        self._backward = lambda: None
        self._prev = set(_children)

    # -- helpers ---------------------------------------------------------
    @property
    def shape(self) -> tuple[int, ...]:
        return self.data.shape

    @staticmethod
    def _as_tensor(x) -> "Tensor":
        return x if isinstance(x, Tensor) else Tensor(x)

    # -- elementwise -----------------------------------------------------
    def __add__(self, other) -> "Tensor":
        other = self._as_tensor(other)
        out = Tensor(self.data + other.data, (self, other), "+")

        def _backward() -> None:
            self.grad += _unbroadcast(out.grad, self.data.shape)
            other.grad += _unbroadcast(out.grad, other.data.shape)

        out._backward = _backward
        return out

    def __mul__(self, other) -> "Tensor":
        other = self._as_tensor(other)
        out = Tensor(self.data * other.data, (self, other), "*")

        def _backward() -> None:
            self.grad += _unbroadcast(other.data * out.grad, self.data.shape)
            other.grad += _unbroadcast(self.data * out.grad, other.data.shape)

        out._backward = _backward
        return out

    def __pow__(self, power: float) -> "Tensor":
        out = Tensor(self.data ** power, (self,), f"**{power}")

        def _backward() -> None:
            self.grad += (power * self.data ** (power - 1)) * out.grad

        out._backward = _backward
        return out

    def __neg__(self) -> "Tensor":
        return self * -1.0

    def __sub__(self, other) -> "Tensor":
        return self + (-self._as_tensor(other))

    def __truediv__(self, other) -> "Tensor":
        other = self._as_tensor(other)
        return self * (other ** -1.0)

    __radd__ = __add__
    __rmul__ = __mul__

    def __rsub__(self, other) -> "Tensor":
        return self._as_tensor(other) + (-self)

    # -- matmul ----------------------------------------------------------
    def __matmul__(self, other) -> "Tensor":
        other = self._as_tensor(other)
        out = Tensor(self.data @ other.data, (self, other), "@")

        def _backward() -> None:
            da = out.grad @ np.swapaxes(other.data, -1, -2)
            db = np.swapaxes(self.data, -1, -2) @ out.grad
            self.grad += _unbroadcast(da, self.data.shape)
            other.grad += _unbroadcast(db, other.data.shape)

        out._backward = _backward
        return out

    # -- reductions ------------------------------------------------------
    def sum(self, axis=None, keepdims: bool = False) -> "Tensor":
        out = Tensor(self.data.sum(axis=axis, keepdims=keepdims), (self,), "sum")

        def _backward() -> None:
            grad = out.grad
            if not keepdims and axis is not None:
                grad = np.expand_dims(grad, axis)
            self.grad += np.broadcast_to(grad, self.data.shape).copy()

        out._backward = _backward
        return out

    def mean(self, axis=None, keepdims: bool = False) -> "Tensor":
        if axis is None:
            count = self.data.size
        else:
            count = self.data.shape[axis]
        return self.sum(axis=axis, keepdims=keepdims) * (1.0 / count)

    # -- shape -----------------------------------------------------------
    def transpose(self, axis1: int = -1, axis2: int = -2) -> "Tensor":
        out = Tensor(np.swapaxes(self.data, axis1, axis2), (self,), "T")

        def _backward() -> None:
            self.grad += np.swapaxes(out.grad, axis1, axis2)

        out._backward = _backward
        return out

    def reshape(self, *shape: int) -> "Tensor":
        out = Tensor(self.data.reshape(*shape), (self,), "reshape")

        def _backward() -> None:
            self.grad += out.grad.reshape(self.data.shape)

        out._backward = _backward
        return out

    def __getitem__(self, key) -> "Tensor":
        """Index/slice along any axis, e.g. t[:, -1, :] or t[:, :T]."""
        out = Tensor(self.data[key], (self,), "getitem")

        def _backward() -> None:
            grad = np.zeros_like(self.data)
            np.add.at(grad, key, out.grad)
            self.grad += grad

        out._backward = _backward
        return out

    # -- nonlinearities --------------------------------------------------
    def relu(self) -> "Tensor":
        out = Tensor(np.maximum(self.data, 0.0), (self,), "relu")

        def _backward() -> None:
            self.grad += (self.data > 0.0) * out.grad

        out._backward = _backward
        return out

    def tanh(self) -> "Tensor":
        t = np.tanh(self.data)
        out = Tensor(t, (self,), "tanh")

        def _backward() -> None:
            self.grad += (1.0 - t * t) * out.grad

        out._backward = _backward
        return out

    def gelu(self) -> "Tensor":
        # tanh approximation of GELU
        c = math_sqrt(2.0 / np.pi)
        x = self.data
        inner = c * (x + 0.044715 * x ** 3)
        t = np.tanh(inner)
        out_data = 0.5 * x * (1.0 + t)
        out = Tensor(out_data, (self,), "gelu")

        def _backward() -> None:
            dt = (1.0 - t * t) * c * (1.0 + 3 * 0.044715 * x ** 2)
            grad = 0.5 * (1.0 + t) + 0.5 * x * dt
            self.grad += grad * out.grad

        out._backward = _backward
        return out

    def exp(self) -> "Tensor":
        e = np.exp(self.data)
        out = Tensor(e, (self,), "exp")

        def _backward() -> None:
            self.grad += e * out.grad

        out._backward = _backward
        return out

    def log(self) -> "Tensor":
        out = Tensor(np.log(self.data + 1e-12), (self,), "log")

        def _backward() -> None:
            self.grad += (1.0 / (self.data + 1e-12)) * out.grad

        out._backward = _backward
        return out

    def sqrt(self) -> "Tensor":
        return self ** 0.5

    def softmax(self, axis: int = -1) -> "Tensor":
        m = self.data.max(axis=axis, keepdims=True)
        e = np.exp(self.data - m)
        s = e / e.sum(axis=axis, keepdims=True)
        out = Tensor(s, (self,), "softmax")

        def _backward() -> None:
            dot = (out.grad * s).sum(axis=axis, keepdims=True)
            self.grad += s * (out.grad - dot)

        out._backward = _backward
        return out

    # -- autodiff --------------------------------------------------------
    def backward(self) -> None:
        topo: list[Tensor] = []
        visited: set[Tensor] = set()

        def build(node: "Tensor") -> None:
            if node not in visited:
                visited.add(node)
                for child in node._prev:
                    build(child)
                topo.append(node)

        build(self)
        self.grad = np.ones_like(self.data)
        for node in reversed(topo):
            node._backward()


def math_sqrt(x: float) -> float:
    return float(np.sqrt(x))


# -- modules ------------------------------------------------------------
class Embedding:
    def __init__(self, num: int, dim: int, rng: np.random.Generator, std: float = 0.02) -> None:
        self.weight = Tensor(rng.standard_normal((num, dim)) * std)
        self.dim = dim

    def __call__(self, idx: np.ndarray) -> Tensor:
        idx = np.asarray(idx)
        out = Tensor(self.weight.data[idx], (self.weight,), "embed")

        def _backward() -> None:
            np.add.at(self.weight.grad, idx, out.grad)

        out._backward = _backward
        return out

    def parameters(self) -> list[Tensor]:
        return [self.weight]


class Linear:
    def __init__(self, fan_in: int, fan_out: int, rng: np.random.Generator, bias: bool = True) -> None:
        std = 1.0 / math_sqrt(fan_in)
        self.weight = Tensor(rng.standard_normal((fan_in, fan_out)) * std)
        self.bias = Tensor(np.zeros(fan_out)) if bias else None

    def __call__(self, x: Tensor) -> Tensor:
        out = x @ self.weight
        if self.bias is not None:
            out = out + self.bias
        return out

    def parameters(self) -> list[Tensor]:
        return [self.weight] if self.bias is None else [self.weight, self.bias]


class LayerNorm:
    def __init__(self, dim: int) -> None:
        self.gain = Tensor(np.ones(dim))
        self.bias = Tensor(np.zeros(dim))

    def __call__(self, x: Tensor) -> Tensor:
        mu = x.mean(axis=-1, keepdims=True)
        centered = x - mu
        var = (centered * centered).mean(axis=-1, keepdims=True)
        normed = centered / (var + 1e-5).sqrt()
        return normed * self.gain + self.bias

    def parameters(self) -> list[Tensor]:
        return [self.gain, self.bias]


def cross_entropy(logits: Tensor, targets: np.ndarray) -> Tensor:
    """Numerically-stable softmax cross-entropy.

    logits: (N, V) Tensor. targets: (N,) int array. Returns scalar Tensor.
    """
    targets = np.asarray(targets)
    n = logits.data.shape[0]
    m = logits.data.max(axis=-1, keepdims=True)
    shifted = logits.data - m
    log_sum = np.log(np.exp(shifted).sum(axis=-1, keepdims=True))
    log_probs = shifted - log_sum  # (N, V)
    loss_val = float(-log_probs[np.arange(n), targets].mean())
    out = Tensor(loss_val, (logits,), "cross_entropy")

    def _backward() -> None:
        probs = np.exp(log_probs)
        probs[np.arange(n), targets] -= 1.0
        logits.grad += (probs / n) * out.grad

    out._backward = _backward
    return out


def zero_grad(params: Iterable[Tensor]) -> None:
    for p in params:
        p.grad = np.zeros_like(p.data)
