from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import json


@dataclass(frozen=True)
class BootstrapResult:
    project_dir: Path
    config_path: Path
    files_written: int


class ProjectBootstrapper:
    def __init__(self, output_dir: Path, name: str, blueprint: str = "studio-ia") -> None:
        self.output_dir = output_dir
        self.name = name
        self.blueprint = blueprint

    def run(self, force: bool = False) -> BootstrapResult:
        if self.blueprint != "studio-ia":
            raise ValueError("Only the 'studio-ia' blueprint is available")

        project_dir = (self.output_dir / self.name).resolve()
        if project_dir.exists() and any(project_dir.iterdir()) and not force:
            raise FileExistsError(f"{project_dir} already exists; pass --force to overwrite blueprint files")

        files = studio_ia_files(self.name)
        for relative, content in files.items():
            path = project_dir / relative
            path.parent.mkdir(parents=True, exist_ok=True)
            if path.exists() and not force:
                continue
            path.write_text(content, encoding="utf-8")

        config_path = project_dir / "autoresearch.config.json"
        config_path.write_text(
            json.dumps(studio_ia_autoresearch_config(self.name), indent=2) + "\n",
            encoding="utf-8",
        )
        return BootstrapResult(project_dir=project_dir, config_path=config_path, files_written=len(files) + 1)


def studio_ia_autoresearch_config(name: str) -> dict[str, object]:
    return {
        "name": f"{name}-mistral-build",
        "workspace": ".",
        "command": "python scripts/score_project.py",
        "metric_regex": "AUTORESEARCH_SCORE:\\s*([0-9.]+)",
        "iterations": 12,
        "seconds_per_trial": 120,
        "maximize": False,
        "patience": 5,
        "baseline_first": True,
        "report": True,
        "agent_provider": "mistral",
        "agent_model": "codestral-latest",
        "agent_temperature": 0.2,
        "agent_max_tokens": 4096,
        "objective_file": "docs/BUILD_PROGRAM.md",
        "agent_files": [
            "src/app.tsx",
            "src/styles.css",
            "src/data/studio.ts",
            "src/components/shell.tsx",
            "src/components/dashboard.tsx",
            "src/components/canvas.tsx",
            "src/components/knowledge-graph.tsx",
            "src/components/owner-console.tsx",
        ],
    }


def studio_ia_files(name: str) -> dict[str, str]:
    title = name.replace("-", " ").replace("_", " ").title()
    return {
        "README.md": f"""# {title}

Clean-room Studio IA starter generated by Autoresearch Lab.

## Run

```powershell
npm install
npm run dev
```

## Improve With Autoresearch + Mistral

```powershell
$env:MISTRAL_API_KEY = "your-key"
python -m autoresearch_lab run --config autoresearch.config.json
```

The scoring script rewards a richer Studio IA structure: navigation, cockpit, canvas, knowledge graph, owner console, strong UI text, and TypeScript source completeness.
""",
        "package.json": """{
  "name": "studio-ia-cleanroom",
  "private": true,
  "type": "module",
  "scripts": {
    "dev": "vite dev",
    "build": "vite build",
    "preview": "vite preview",
    "typecheck": "tsc --noEmit"
  },
  "dependencies": {
    "@vitejs/plugin-react": "^5.0.4",
    "vite": "^7.3.1",
    "typescript": "^5.8.3",
    "react": "^19.2.0",
    "react-dom": "^19.2.0",
    "lucide-react": "^0.575.0"
  },
  "devDependencies": {}
}
""",
        "index.html": """<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Studio IA</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
""",
        "tsconfig.json": """{
  "compilerOptions": {
    "target": "ES2022",
    "useDefineForClassFields": true,
    "lib": ["DOM", "DOM.Iterable", "ES2022"],
    "allowJs": false,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "ESNext",
    "moduleResolution": "Bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": ["src"]
}
""",
        "vite.config.ts": """import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';

export default defineConfig({
  plugins: [react()],
});
""",
        "src/main.tsx": """import React from 'react';
import { createRoot } from 'react-dom/client';
import { StudioApp } from './app';
import './styles.css';

createRoot(document.getElementById('root')!).render(
  <React.StrictMode>
    <StudioApp />
  </React.StrictMode>,
);
""",
        "src/app.tsx": """import { StudioShell } from './components/shell';
import { Dashboard } from './components/dashboard';
import { CanvasWorkspace } from './components/canvas';
import { KnowledgeGraph } from './components/knowledge-graph';
import { OwnerConsole } from './components/owner-console';
import { studioProjects } from './data/studio';

export function StudioApp() {
  return (
    <StudioShell>
      <Dashboard projects={studioProjects} />
      <CanvasWorkspace />
      <KnowledgeGraph />
      <OwnerConsole />
    </StudioShell>
  );
}
""",
        "src/components/shell.tsx": """import type { ReactNode } from 'react';

const navItems = ['Projects', 'Cockpit', 'Canvas', 'Knowledge', 'Owner'];

export function StudioShell({ children }: { children: ReactNode }) {
  return (
    <div className="studio-shell">
      <aside className="sidebar">
        <div className="brand">Studio IA</div>
        <nav>
          {navItems.map((item) => (
            <a href={`#${item.toLowerCase()}`} key={item}>{item}</a>
          ))}
        </nav>
      </aside>
      <main className="workspace">{children}</main>
    </div>
  );
}
""",
        "src/components/dashboard.tsx": """import type { StudioProject } from '../data/studio';

export function Dashboard({ projects }: { projects: StudioProject[] }) {
  return (
    <section id="projects" className="panel">
      <div className="panel-heading">
        <span>Project OS</span>
        <h1>Creative production cockpit</h1>
      </div>
      <div className="project-grid">
        {projects.map((project) => (
          <article className="project-card" key={project.id}>
            <strong>{project.name}</strong>
            <p>{project.mission}</p>
            <small>{project.status} · {project.assets} assets · {project.risk} risk</small>
          </article>
        ))}
      </div>
    </section>
  );
}
""",
        "src/components/canvas.tsx": """const frames = ['Script spine', 'Moodboard', 'Shot list', 'Delivery map'];

export function CanvasWorkspace() {
  return (
    <section id="canvas" className="panel split">
      <div>
        <span>Canvas</span>
        <h2>Visual workspace</h2>
        <p>Arrange frames, bind media evidence, and promote approved concepts.</p>
      </div>
      <div className="frame-board">
        {frames.map((frame) => <button key={frame}>{frame}</button>)}
      </div>
    </section>
  );
}
""",
        "src/components/knowledge-graph.tsx": """const nodes = ['Mission', 'Scene', 'Asset', 'Decision', 'Client'];

export function KnowledgeGraph() {
  return (
    <section id="knowledge" className="panel">
      <span>Knowledge graph</span>
      <h2>Evidence-backed decisions</h2>
      <div className="graph-row">
        {nodes.map((node) => <div className="node" key={node}>{node}</div>)}
      </div>
    </section>
  );
}
""",
        "src/components/owner-console.tsx": """const checks = ['Provider routing', 'Usage costs', 'Role guards', 'Release notes'];

export function OwnerConsole() {
  return (
    <section id="owner" className="panel">
      <span>Owner console</span>
      <h2>Operate the studio</h2>
      <ul className="check-list">
        {checks.map((check) => <li key={check}>{check}</li>)}
      </ul>
    </section>
  );
}
""",
        "src/data/studio.ts": """export type StudioProject = {
  id: string;
  name: string;
  mission: string;
  status: 'active' | 'review' | 'blocked';
  assets: number;
  risk: 'low' | 'medium' | 'high';
};

export const studioProjects: StudioProject[] = [
  {
    id: 'p-001',
    name: 'Orystia launch film',
    mission: 'Build a cinematic launch package with client-ready evidence.',
    status: 'active',
    assets: 42,
    risk: 'medium',
  },
  {
    id: 'p-002',
    name: 'Knowledge graph proof',
    mission: 'Map creative decisions to references, assets, and approvals.',
    status: 'review',
    assets: 18,
    risk: 'low',
  },
];
""",
        "src/styles.css": """:root {
  color: #172033;
  background: #f5f7fa;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
}

body { margin: 0; }

.studio-shell {
  display: grid;
  grid-template-columns: 248px 1fr;
  min-height: 100vh;
}

.sidebar {
  background: #101828;
  color: white;
  padding: 24px;
}

.brand {
  font-size: 22px;
  font-weight: 800;
  margin-bottom: 28px;
}

nav {
  display: grid;
  gap: 10px;
}

nav a {
  color: #d9e2f2;
  text-decoration: none;
  padding: 10px 0;
}

.workspace {
  display: grid;
  gap: 20px;
  padding: 28px;
}

.panel {
  background: white;
  border: 1px solid #d8dee8;
  border-radius: 8px;
  padding: 22px;
}

.panel span {
  color: #1769aa;
  font-size: 12px;
  font-weight: 800;
  text-transform: uppercase;
}

h1, h2, p { margin-top: 0; }

.project-grid {
  display: grid;
  gap: 14px;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
}

.project-card, .node, .frame-board button {
  border: 1px solid #d8dee8;
  border-radius: 8px;
  padding: 14px;
}

.split {
  display: grid;
  gap: 20px;
  grid-template-columns: 1fr 1.5fr;
}

.frame-board, .graph-row {
  display: flex;
  flex-wrap: wrap;
  gap: 12px;
}

.frame-board button {
  background: #eef6ff;
  color: #0d4f85;
  font: inherit;
}

.node {
  background: #f6f7f9;
  font-weight: 700;
}

.check-list {
  display: grid;
  gap: 8px;
}

@media (max-width: 820px) {
  .studio-shell, .split {
    grid-template-columns: 1fr;
  }
}
""",
        "scripts/score_project.py": """from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
REQUIRED = [
    'src/app.tsx',
    'src/components/shell.tsx',
    'src/components/dashboard.tsx',
    'src/components/canvas.tsx',
    'src/components/knowledge-graph.tsx',
    'src/components/owner-console.tsx',
    'src/data/studio.ts',
    'src/styles.css',
]
KEYWORDS = [
    'project',
    'cockpit',
    'canvas',
    'knowledge',
    'owner',
    'asset',
    'decision',
    'risk',
    'evidence',
    'workspace',
]


def main() -> None:
    missing = [path for path in REQUIRED if not (ROOT / path).exists()]
    text = ''
    for path in REQUIRED:
        candidate = ROOT / path
        if candidate.exists():
            text += candidate.read_text(encoding='utf-8', errors='ignore').lower() + '\\n'

    keyword_hits = sum(1 for keyword in KEYWORDS if keyword in text)
    size_bonus = min(len(text) / 20000, 1.0)
    structure_penalty = len(missing) * 0.15
    keyword_penalty = (len(KEYWORDS) - keyword_hits) * 0.06
    score = max(0.0, 1.0 - size_bonus + structure_penalty + keyword_penalty)
    print(f'AUTORESEARCH_SCORE: {score:.6f}')
    if missing:
        print('missing:', ', '.join(missing))


if __name__ == '__main__':
    main()
""",
        "docs/BUILD_PROGRAM.md": """# Build Program

Autoresearch should improve this project toward a Studio IA platform:

- premium project dashboard
- creative cockpit
- canvas workspace
- knowledge graph
- owner/admin console
- provider and cost visibility
- evidence-backed decisions
- responsive production UI

Each trial should make one coherent improvement and keep the project runnable.
""",
    }
